# Generated by Django 3.0.8 on 2020-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(max_length=500)),
                ('head1', models.CharField(max_length=500)),
                ('head2', models.CharField(max_length=500)),
                ('thumbmail', models.ImageField(upload_to='blog/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
